# -*- coding: utf-8 -*-
"""OTP Cracker.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CwG-vOneo7zSUGp5Hr4qO5031aXxydAE
"""

#otp_cracker
from random import randint
real_OTP= input("Enter OTP")
OTP= ['0','1','2','3', '4', '5', '6', '7', '8', '9']
guess=''

while(guess!= real_OTP):
  guess=''
  for letter in range(len(real_OTP)):
    guess_letter= OTP[randint(0,9)]
    guess=str(guess_letter)+ str(guess)
    print(guess)
    print()